# Generated by Django 2.2.5 on 2020-02-14 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='dead_line',
            field=models.DateField(default=datetime.datetime(2020, 2, 14, 9, 45, 9, 882403, tzinfo=utc), verbose_name='締め切り'),
        ),
    ]
